app_config = {
    "stocks": [
        {"id": "ALUA", "country": "Argentina", "symbol": "ALUA", "name": "Aluar",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=ALUA&csv=1"},
        {"id": "AGRO", "country": "Argentina", "symbol": "AGRO", "name": "Agrometal S.A.I.",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=AGRO&csv=1"},
        {"id": "APBR", "country": "Argentina", "symbol": "APBR", "name": "Petrobras",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=APBR&csv=1"},
        {"id": "BMA", "country": "Argentina", "symbol": "BMA", "name": "Banco Macro",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=BMA&csv=1"},
        {"id": "CARC", "country": "Argentina", "symbol": "CARC", "name": "Carboclor S.A.",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=CARC&csv=1"},
        {"id": "CECO2", "country": "Argentina", "symbol": "CECO2", "name": "Endesa Costanera S.A.",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=CECO2&csv=1"},
        {"id": "CELU", "country": "Argentina", "symbol": "CELU", "name": "Celulosa Argentina S.A.",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=CELU&csv=1"},
        {"id": "CEPU", "country": "Argentina", "symbol": "CEPU", "name": "Central Puerto S.A.",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=CEPU&csv=1"},
        {"id": "CRES", "country": "Argentina", "symbol": "CRES", "name": "Cresud S.A.",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=CRES&csv=1"},
        {"id": "CTIO", "country": "Argentina", "symbol": "CTIO", "name": "Consultatio S.A.",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=CTIO&csv=1"},
        {"id": "EDN", "country": "Argentina", "symbol": "EDN", "name": "Edenor S.A.",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=EDN&csv=1"},
        {"id": "ERAR", "country": "Argentina", "symbol": "ERAR", "name": "Siderar",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=ERAR&csv=1"},
        {"id": "FRAN", "country": "Argentina", "symbol": "FRAN", "name": "BBVA Banco Frances",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=FRAN&csv=1"},
        {"id": "GGAL", "country": "Argentina", "symbol": "GGAL", "name": "Grupo Financiero Galicia",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=GGAL&csv=1"},
        {"id": "JMIN", "country": "Argentina", "symbol": "JMIN", "name": "Holcim Argentina",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=JMIN&csv=1"},
        {"id": "MIRG", "country": "Argentina", "symbol": "MIRG", "name": "Mirgor S.A.",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=MIRG&csv=1"},
        {"id": "PAMP", "country": "Argentina", "symbol": "PAMP", "name": "Pampa Energia S.A.",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=PAMP&csv=1"},
        {"id": "PETR", "country": "Argentina", "symbol": "PETR", "name": "Petrolera Pampa S.A.",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=PETR&csv=1"},
        {"id": "PSUR", "country": "Argentina", "symbol": "PSUR", "name": "Petrolera del Conosur",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=PSUR&csv=1"},
        {"id": "TGSU2", "country": "Argentina", "symbol": "TGSU2", "name": "Transportadora de Gas del Sur",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=TGSU2&csv=1"},
        {"id": "TRAN", "country": "Argentina", "symbol": "TRAN", "name": "Transener",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=TRAN&csv=1"},
        {"id": "TS", "country": "Argentina", "symbol": "TS", "name": "Tenaris",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=TS&csv=1"},
        {"id": "YPFD", "country": "Argentina", "symbol": "YPFD", "name": "YPF",
         "url": "http://www.ravaonline.com/v2/empresas/precioshistoricos.php?e=YPFD&csv=1"}
    ],
    "common_config": {
        "path": "data"
    }
}
